### ISSUE TITLE
Failed to compile with hhvm 3.9.0

### ISSUE THREAD

**Issue by dieend** [chregu/hhvm-newrelic-ext#36]
```
me@pc:/opt/newrelic_extension# git log
commit 78b4fedb01e3098dfea2845aaf6d9e52c29ba9e3
Author: Christian Stocker <me@chregu.tv>
Date:   Mon May 25 11:09:20 2015 +0200

    adjust readme for 3.7

me@pc:/opt/newrelic_extension# hphpize 
** hphpize complete, now run `cmake . && make` to build, `make test` to test

me@pc:/opt/newrelic_extension# cmake .
-- Configuring for HHVM API version 20150212
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/newrelic_extension

me@pc:/opt/newrelic_extension# make
[ 50%] Building CXX object CMakeFiles/newrelic.dir/newrelic.cpp.o
/opt/newrelic_extension/newrelic.cpp:5:46: fatal error: hphp/runtime/ext/ext_hotprofiler.h: No such file or directory
 #include "hphp/runtime/ext/ext_hotprofiler.h"
                                              ^
compilation terminated.
make[2]: *** [CMakeFiles/newrelic.dir/newrelic.cpp.o] Error 1
make[1]: *** [CMakeFiles/newrelic.dir/all] Error 2
make: *** [all] Error 2

me@pc:/opt/newrelic_extension# hhvm --version
HipHop VM 3.9.0 (rel)
Compiler: tags/HHVM-3.9.0-0-ga047a8f8fca8c5a0dd9021867836373ec3e40372
Repo schema: fafdc6abbd9526735214b1d74b58289707518e4f

```

**Comment by noorr-lxr** [comment]
"hphp/runtime/ext/ext_hotprofiler.h" has been moved under "hphp/runtime/ext/hotprofiler/ext_hotprofiler.h".  You need to make the necessary changes in the newrelic.cpp file when including the header files.

**Comment by craig-russell** [comment]
I've made the necessary changes, confirmed that it works in my dev environment, and submitted a pull request: https://github.com/chregu/hhvm-newrelic-ext/pull/37

**Comment by mikaelmattsson** [comment]
+1

**Comment by Qoto** [comment]
+1

**Comment by radriaanse** [comment]
+1 
Working on ArchLinux

**Comment by craigcarnell** [comment]
I get:

```
Sep  9 10:53:11 web kernel: [10079347.903083] init: hhvm main process (7493) terminated with status 255
Sep  9 10:53:11 web kernel: [10079347.903096] init: hhvm main process ended, respawning
```

**Comment by Preen** [comment]
+ 1 @craigcarnell

**Comment by dieend** [comment]
https://github.com/chregu/hhvm-newrelic-ext/pull/37 fix this. closing this issue. Let's move to https://github.com/chregu/hhvm-newrelic-ext/issues/45
